Score page
RafaelAugustScherer/trybe-rank pull request #10
Opened 2022-02-01 15:19 UTC by Ply3r

Principais objetivos desse Pull Request:

- [x] Criar endpoint para o update das questions completed do usuario.
- [ ] Criar função no front para fazer uma requisição para o endpoint criado.
- [ ] Criar pagina de pontuação.
- [ ] Fazer o sistema de barra de porcentagem funcionar de acordo com o tanto de questions completed.
- [ ] CSS: pagina de score.

2022-02-02 15:35 UTC, RafaelAugustScherer requested changes
Coisinhas pequenas a serem mudadas, mas como um todo o código está excelente! Parabéns!! ⭐

2022-02-02 15:35 UTC, RafaelAugustScherer commented on client/src/components/quizButton.jsx
> +    const correctAnswer = userAnswers.filter(({ correct }) => correct);
A forma de filtrar por questões corretas apenas ficou mto boa, sem a necessidade de comparação por ids 🚀

2022-02-02 15:35 UTC, RafaelAugustScherer commented on server/routes/users.js
>    .get(autenticateToken, async (req, res) => {
Pequena correção. Na verdade seria authenticateToken 🧐

2022-02-02 16:10 UTC, Ply3r commented on client/src/components/quizButton.jsx
> +            setUserAnswers([...userAnswers, { question_id: key, answer: value, questions, correct: isCorrect }])
ok, acho uma boa ideia!

2022-02-02 16:11 UTC, Ply3r commented on client/src/components/scoreCard.jsx
> +      <h4>{ hits }</h4>
entendi, boa ideia

2022-02-05 17:50 UTC, RafaelAugustScherer approved these changes

2022-02-05 17:50 UTC, merged