Página Home
RafaelAugustScherer/trybe-rank pull request #13
Opened 2022-02-07 15:04 UTC by RafaelAugustScherer

- [x] Card de Perfil + Edição de dados
- [x] Seção de Acesso Rápido
- [x] Seção de Progresso nos Quizes
- [x] Seção de Leaderboard
- [x] Estilização da página

2022-02-07 16:14 UTC, Ply3r requested changes
Ficou muito boa a pagina, porem tem muito código repetido de outras paginas podemos melhorar isso, e tem algumas questões de design que eu vou comentar com você

2022-02-07 16:14 UTC, Ply3r commented on client/src/components/profileCard.jsx
> +            </p>
Daora essa implementação de editar na home, mais o'que acha de criarmos uma pagina so para isso onde o usuario pode adicionar uma imagem, e deixar esse card com algumas info como pontuação de quiz e posição no rank

2022-02-07 16:14 UTC, Ply3r commented on client/src/components/progressBar.jsx
> +    return value ? Math.round(value) : 0;
Daora, concertou o erro do NaN 👍🏼

2022-02-07 16:14 UTC, Ply3r commented on client/src/components/quizButton.jsx
> +    const headers = { Authorization: token }
caraca, não sabia que funcionava sem o formato de JSON

2022-02-07 16:14 UTC, Ply3r commented on client/src/pages/Home.jsx
> +  };
Temos que arrumar esse código repetido do progressbar

2022-02-07 16:14 UTC, Ply3r commented on client/src/pages/Home.jsx
> +  }
Mesma coisa do comentário do createQuestionsCards

2022-02-07 16:24 UTC, RafaelAugustScherer commented on client/src/components/progressBar.jsx
> +    return value ? Math.round(value) : 0;
👍

2022-02-07 16:25 UTC, RafaelAugustScherer commented on client/src/components/quizButton.jsx
> +    const headers = { Authorization: token }
Sim, descobri com alguns testes na hora de fazer a rota PUT('/user') hehe 😆

2022-02-08 02:45 UTC, RafaelAugustScherer commented on client/src/pages/Home.jsx
> +  };
Beleza, essa parte está arrumada!! 🚀

2022-02-08 15:27 UTC, RafaelAugustScherer commented on client/src/pages/Home.jsx
> +  }
Ok, essa parte ta resolvida também

2022-02-08 21:39 UTC, Ply3r requested changes

2022-02-08 21:39 UTC, Ply3r commented on client/src/pages/Home.jsx
> +      console.log(thisPlayer.score, newRank);
tirar console.log

2022-02-08 21:39 UTC, Ply3r commented on client/src/providers/InfoProvider.js
> +  });
acho q essa info, poderia ficar salva na home mesmo, do jeito que esta ela n se atualiza apos o usuário fazer um quiz!

2022-02-08 21:39 UTC, Ply3r commented on client/src/providers/TypeCardsProvider.js
> +}
Não vejo o porque de criar um provider para o tipo, já que somente ha a relação de troca pai para filho, poderia deixar no TypeCards como estava.

2022-02-08 21:39 UTC, Ply3r commented on client/src/utils/leaderboard.js
> +};
Gostei que separou para uma função de pegar a soma de todos os quizes, e uma que filtra ficou bem legível! 👍🏼

2022-02-08 21:47 UTC, RafaelAugustScherer commented on client/src/pages/Home.jsx
> +    const thisPlayer = newPlayers.find(({nickname: ply3rNickname}) => ply3rNickname === nickname);
Nem percebi 😆

2022-02-08 21:51 UTC, RafaelAugustScherer commented on client/src/pages/Home.jsx
> +      console.log(thisPlayer.score, newRank);
Ok

2022-02-08 22:04 UTC, RafaelAugustScherer commented on client/src/providers/InfoProvider.js
> +  });
Tem razão, na verdade coloquei ali por engano. Estava fazendo uns testes 👍

2022-02-08 22:04 UTC, RafaelAugustScherer commented on client/src/utils/leaderboard.js
> +};
Boa, valeu!!

2022-02-08 22:07 UTC, RafaelAugustScherer commented on client/src/providers/TypeCardsProvider.js
> +}
Na verdade eu separei essas 2 variáveis porque elas eram passadas múltiplas vezes como props para os cards de tipo. Acabava que ocupava muita linha de código.
Teria que passar de Select-Quiz -> TypeCards -> TypeCard -> ProgressBar.
O processo acaba sendo um prop-drilling não acha? Será que tem alguma solução melhor?

2022-02-09 13:19 UTC, Ply3r commented on client/src/providers/TypeCardsProvider.js
> +}
acho que poderia passar o select e o active para o typeCards

2022-02-09 14:32 UTC, Ply3r commented on client/src/providers/TypeCardsProvider.js
> +}
Pode deixar desse jeito mesmo então o typeCards já ta muito sobrecarregado

2022-02-12 14:00 UTC, Ply3r approved these changes

2022-02-12 14:00 UTC, merged